AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AreaRestrictionsMonitor

  Sample SAM Template for AreaRestrictionsMonitor

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  AreaRestrictionsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: area_restrictions/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        AreaRestrictions:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AreaRestrictionsApi:
    Description: "API Gateway endpoint URL for Prod stage for Area Restrictions function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  AreaRestrictionsFunction:
    Description: "Area Restrictions Lambda Function ARN"
    Value: !GetAtt AreaRestrictionsFunction.Arn
  AreaRestrictionsFunctionIamRole:
    Description: "Implicit IAM Role created for Area Restrictions function"
    Value: !GetAtt AreaRestrictionsFunctionRole.Arn
