/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 22-Jul-2022 11:13:50 AM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfnews"."published_incident_detail"
(
	"published_incident_detail_guid" VARCHAR(36) NOT NULL,    -- PUBLISHED_INCIDENT_DETAIL_GUID is a unique identifier for the record.
	"incident_guid" VARCHAR(36) NOT NULL,    -- INCIDENT_GUID: Is a foreign key to INCIDENT: Incident provides a record to manage, monitor and track an event that is of interest to the BCWS. An incident can be of different types, and is not necessarily always a fire. 
	"incident_number_label" VARCHAR(25) NOT NULL,    -- The Incident Number Label (a.k.a. Fire Number) is the common "short name" that will be used to reference the Incident throughout its lifecycle. The format of the Incident Number depends on the Incident Type. For most Incidents it will be comprised of:  	- the Fire Centre (Administrative) letter  	- the Zone (Administrative) number  	- the incident ID sequence number (eg. P30232)   The incident number could also be 2017-0232
	"news_created_timestamp" timestamp NOT NULL,    -- News Created Timestamp is the date and time the news publication was created.
	"stage_of_control_code" varchar(10)	 NULL,    -- STAGE_OF_CONTROL_CODE: Is a foreign key to STAGE_OF_CONTROL_CODE: Stage of Control Code describes the degree to which the incident is under control:  	- Out of Control    	- Being Held    	- Under Control    	- Out   Reports and selections should present values in order prescribed above.   
	"general_incident_cause_cat_id" decimal(15) NULL,    -- GENERAL_INCIDENT_CAUSE_CAT_ID: Is a foreign key to GENERAL_INCIDENT_CAUSE_CAT: General Incident Cause Category answers the question "Was the Incident started by humans, nature, or undetermined?".  This is referred to as (A) currently in the Cause Code structure.   The values include: * Human * Nature * Undetermined 
	"general_incident_cause_cat" varchar(40) NULL,    -- General Incident Cause Category indicates the cause of the incident.
	"news_publication_status_code" varchar(10)	 NULL,    -- NEWS_PUBLICATION_STATUS_CODE: Is a foreign key to NEWS_PUBLICATION_STATUS_CODE: News Publication Status Code tracks the state of a news publication.  Values are:  	- Draft 	- Published 	- Rescinded 	- Archived
	"discovery_date" timestamp NULL,    -- Discovery Date is the date and time that the fire was first discovered. This may be hours before it is first reported to BCWS.
	"fire_zone_org_unit_identifier" decimal(10) NULL,    -- Org Unit Identifier is a unique number assigned to the org unit that remains consistent across temporal periods.  The geographic boundary of the org unit may change a bit over time, and the name of the org unit may change over time, but the business are still recognizes the org unit as being the same regardless of these minor changes.  Thus the Org Unit Key is used to create a consistent key to reference the org unit across temporal periods, that does not change over time.
	"fire_of_note_ind" varchar(1)	 NOT NULL DEFAULT 'N',    -- Fire of Note Ind indicates whether a fire is of note (Y) or not (N). A fire of note is a fire of interest, due to its visibility and/or potential threat, and so information about the fire will be published within government and possibly to the public.  Currently, information about such fires is published through social media and the BCWS Wildfire News application, which is a source of information for the BCWS web pages. 
	"incident_name" varchar(100)	 NULL,    -- Incident Name is the public name given to the Incident, given by BCWS, the media, a municipality, etc. Used in communications with the public. BCWS does not require an Incident have a name. Note: fiResponse may set this by default, e.g. to the Landscape Unit.
	"incident_location" varchar(4000)	 NULL,
	"incident_overview" text NULL,    -- Incident Overview contains a rich text overview of the incident, which may contain 
	"traditional_territory_detail" varchar(1000)	 NULL,
	"incident_size_type" varchar(25)	 NULL,    -- Incident Size Type describes the type of size measurement to be published. IE the Estimated Incident Size or the Mapped Incident Size.
	"incident_size_estimated_ha" decimal(10,3) NULL,    -- Incident Size Estimated Ha is the estimated size of the incident, measured in hectares, to three decimals (e.g., 0.001).
	"incident_size_mapped_ha" decimal(10,3) NULL,    -- Incident Size Mapped Ha is the mapped size of the incident, measured in hectares, to three decimals (e.g., 0.001).
	"incident_size_detail" varchar(4000)	 NULL,    -- Incident Size Detail provides information about the size of the incident such as disclaimers or how the size information was arrived at.
	"incident_cause_detail" varchar(4000)	 NULL,    -- Incident Cause Detail provides information about the cause of the incident such as disclaimers or how the cause information was arrived at.
	"contact_org_unit_identifier" decimal(10) NULL,    -- Contact Org Unit Identifier is a unique number assigned to the org unit that remains consistent across temporal periods.   The geographic boundary of the org unit may change a bit over time, and the name of the org unit may change over time, but the business are still recognizes the org unit as being the same regardless of these minor changes.  Thus the Org Unit Key is used to create a consistent key to reference the org unit across temporal periods, that does not change over time.
	"contact_phone_number" varchar(25)	 NULL,    -- Contact Phone Number is the phone number used to contact the fire centre regarding an Incident.
	"contact_email_address" varchar(100)	 NULL,    -- Contact email address is the email address used to contact the fire centre regarding an Incident.
	"resource_detail" varchar(4000)	 NULL,    -- Resource Detail contains disclaimers and details about the resources collectively utilized to control the incident.
	"wildfire_crew_resources_ind" varchar(1)	 NOT NULL DEFAULT 'N',    -- Wildfire Crews Resources Ind indicates whether wildfire crew resources are being utilized to get the incident under control (Y) or not (N).
	"wildfire_crew_resources_detail" varchar(4000)	 NULL,    -- Wildfire Crews Resources Detail contains details regarding the wildfire crew resources utilized on the incident.
	"wildfire_aviation_resource_ind" varchar(1)	 NOT NULL,    -- Wildfire Aviation Resources Ind indicates whether wildfire aviation resources are being utilized to get the incident under control (Y) or not (N).
	"wildfire_aviation_rsrc_detail" varchar(4000)	 NULL,    -- Wildfire Aviation Resources Detail contains details regarding the wildfire aviation resources utilized on the incident.
	"heavy_equipment_resources_ind" varchar(1)	 NOT NULL,    -- Heavy Equipment Resources Ind indicates whether heavy equipment resources are being utilized to get the incident under control (Y) or not (N).
	"heavy_equipment_resources_dtl" varchar(4000)	 NULL,    -- Heavy Equipment Resources Detail contains details regarding the heavy equipment resources utilized on the incident.
	"incident_mgmnt_crew_rsrc_ind" varchar(1)	 NOT NULL,    -- Incident Management Crews Resources Ind indicates whether incident management crew resources are being utilized to get the incident under control (Y) or not (N).
	"incident_mgmnt_crew_rsrc_dtl" varchar(4000)	 NULL,    -- Incident Management Crew Resources Detail contains details regarding the incident management crew resources utilized on the incident.
	"structure_protection_rsrc_ind" varchar(1)	 NOT NULL,    -- Structure Protection Resources Ind indicates whether structure protection resources are being utilized to get the incident under control (Y) or not (N).
	"structure_protection_rsrc_dtl" varchar(4000)	 NULL,    -- Structure Protection Resources Detail contains details regarding the structure protection resources utilized on the incident.
	"published_timestamp" timestamp NULL,    -- Published Timestamp is the date and time the news publication was published. 
	"published_user_type_code" varchar(3)	 NULL,    -- Published User Type Code is the User Type Code as defined in the WebADE database, that defines the type of the user.  User types defined in WebADE are BC Services Card, Government, Business Partner, Unverified, Individual, Verified Individual, Service Client.
	"published_user_guid" varchar(32)	 NULL,    -- Published User Guid is the user GUID identifying the person who published the news publication.
	"published_user_userid" varchar(100)	 NULL,    -- Published User Userid is the IDIR or BCEID userid of the  person who published the news publication.
	"published_user_name" varchar(100)	 NULL,    -- Published User Name is the name of the person who published the news publication.
	"last_updated_timestamp" timestamp NULL,    -- Last Updated Timestamp is the date and time the  record was last updated.
	"revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64)	 NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" timestamp NOT NULL DEFAULT current_date,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64)	 NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" timestamp NOT NULL DEFAULT current_date    -- UPDATE_DATE is the date and time the row of data was updated.
)
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "wfnews"."published_incident_detail"
	IS 'Published Incident Detail is used to track the best known information about an incident at a specific point in time which is published as news to the general public. The ministry shares news about active incidents with the general public, and it is important to publish the best known information about the incident at that time even though the current information about the incident is changing dynamically during control efforts.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."published_incident_detail_guid"
	IS 'PUBLISHED_INCIDENT_DETAIL_GUID is a unique identifier for the record.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."incident_guid"
	IS 'INCIDENT_GUID: Is a foreign key to INCIDENT: Incident provides a record to manage, monitor and track an event that is of interest to the BCWS. An incident can be of different types, and is not necessarily always a fire. '
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."incident_number_label"
	IS 'The Incident Number Label (a.k.a. Fire Number) is the common "short name" that will be used to reference the Incident throughout its lifecycle. The format of the Incident Number depends on the Incident Type. For most Incidents it will be comprised of:  	- the Fire Centre (Administrative) letter  	- the Zone (Administrative) number  	- the incident ID sequence number (eg. P30232)   The incident number could also be 2017-0232'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."news_created_timestamp"
	IS 'News Created Timestamp is the date and time the news publication was created.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."stage_of_control_code"
	IS 'STAGE_OF_CONTROL_CODE: Is a foreign key to STAGE_OF_CONTROL_CODE: Stage of Control Code describes the degree to which the incident is under control:  	- Out of Control    	- Being Held    	- Under Control    	- Out   Reports and selections should present values in order prescribed above.   '
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."general_incident_cause_cat_id"
	IS 'GENERAL_INCIDENT_CAUSE_CAT_ID: Is a foreign key to GENERAL_INCIDENT_CAUSE_CAT: General Incident Cause Category answers the question "Was the Incident started by humans, nature, or undetermined?".  This is referred to as (A) currently in the Cause Code structure.   The values include: * Human * Nature * Undetermined '
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."news_publication_status_code"
	IS 'NEWS_PUBLICATION_STATUS_CODE: Is a foreign key to NEWS_PUBLICATION_STATUS_CODE: News Publication Status Code tracks the state of a news publication.  Values are:  	- Draft 	- Published 	- Rescinded 	- Archived'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."discovery_date"
	IS 'Discovery Date is the date and time that the fire was first discovered. This may be hours before it is first reported to BCWS.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."general_incident_cause_cat"
	IS 'General Incident Cause Category indicates the cause of the incident.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."fire_zone_org_unit_identifier"
	IS 'Org Unit Identifier is a unique number assigned to the org unit that remains consistent across temporal periods.  The geographic boundary of the org unit may change a bit over time, and the name of the org unit may change over time, but the business are still recognizes the org unit as being the same regardless of these minor changes.  Thus the Org Unit Key is used to create a consistent key to reference the org unit across temporal periods, that does not change over time.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."fire_of_note_ind"
	IS 'Fire of Note Ind indicates whether a fire is of note (Y) or not (N). A fire of note is a fire of interest, due to its visibility and/or potential threat, and so information about the fire will be published within government and possibly to the public.  Currently, information about such fires is published through social media and the BCWS Wildfire News application, which is a source of information for the BCWS web pages. '
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."incident_name"
	IS 'Incident Name is the public name given to the Incident, given by BCWS, the media, a municipality, etc. Used in communications with the public. BCWS does not require an Incident have a name. Note: fiResponse may set this by default, e.g. to the Landscape Unit.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."incident_overview"
	IS 'Incident Overview contains a rich text overview of the incident, which may contain '
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."incident_size_type"
	IS 'Incident Size Type describes the type of size measurement to be published. IE the Estimated Incident Size or the Mapped Incident Size.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."incident_size_estimated_ha"
	IS 'Incident Size Estimated Ha is the estimated size of the incident, measured in hectares, to three decimals (e.g., 0.001).'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."incident_size_mapped_ha"
	IS 'Incident Size Mapped Ha is the mapped size of the incident, measured in hectares, to three decimals (e.g., 0.001).'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."incident_size_detail"
	IS 'Incident Size Detail provides information about the size of the incident such as disclaimers or how the size information was arrived at.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."incident_cause_detail"
	IS 'Incident Cause Detail provides information about the cause of the incident such as disclaimers or how the cause information was arrived at.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."contact_org_unit_identifier"
	IS 'Contact Org Unit Identifier is a unique number assigned to the org unit that remains consistent across temporal periods.   The geographic boundary of the org unit may change a bit over time, and the name of the org unit may change over time, but the business are still recognizes the org unit as being the same regardless of these minor changes.  Thus the Org Unit Key is used to create a consistent key to reference the org unit across temporal periods, that does not change over time.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."contact_phone_number"
	IS 'Contact Phone Number is the phone number used to contact the fire centre regarding an Incident.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."contact_email_address"
	IS 'Contact email address is the email address used to contact the fire centre regarding an Incident.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."resource_detail"
	IS 'Resource Detail contains disclaimers and details about the resources collectively utilized to control the incident.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."wildfire_crew_resources_ind"
	IS 'Wildfire Crews Resources Ind indicates whether wildfire crew resources are being utilized to get the incident under control (Y) or not (N).'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."wildfire_crew_resources_detail"
	IS 'Wildfire Crews Resources Detail contains details regarding the wildfire crew resources utilized on the incident.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."wildfire_aviation_resource_ind"
	IS 'Wildfire Aviation Resources Ind indicates whether wildfire aviation resources are being utilized to get the incident under control (Y) or not (N).'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."wildfire_aviation_rsrc_detail"
	IS 'Wildfire Aviation Resources Detail contains details regarding the wildfire aviation resources utilized on the incident.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."heavy_equipment_resources_ind"
	IS 'Heavy Equipment Resources Ind indicates whether heavy equipment resources are being utilized to get the incident under control (Y) or not (N).'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."heavy_equipment_resources_dtl"
	IS 'Heavy Equipment Resources Detail contains details regarding the heavy equipment resources utilized on the incident.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."incident_mgmnt_crew_rsrc_ind"
	IS 'Incident Management Crews Resources Ind indicates whether incident management crew resources are being utilized to get the incident under control (Y) or not (N).'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."incident_mgmnt_crew_rsrc_dtl"
	IS 'Incident Management Crew Resources Detail contains details regarding the incident management crew resources utilized on the incident.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."structure_protection_rsrc_ind"
	IS 'Structure Protection Resources Ind indicates whether structure protection resources are being utilized to get the incident under control (Y) or not (N).'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."structure_protection_rsrc_dtl"
	IS 'Structure Protection Resources Detail contains details regarding the structure protection resources utilized on the incident.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."published_timestamp"
	IS 'Published Timestamp is the date and time the news publication was published. '
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."published_user_type_code"
	IS 'Published User Type Code is the User Type Code as defined in the WebADE database, that defines the type of the user.  User types defined in WebADE are BC Services Card, Government, Business Partner, Unverified, Individual, Verified Individual, Service Client.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."published_user_guid"
	IS 'Published User Guid is the user GUID identifying the person who published the news publication.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."published_user_userid"
	IS 'Published User Userid is the IDIR or BCEID userid of the  person who published the news publication.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."published_user_name"
	IS 'Published User Name is the name of the person who published the news publication.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."last_updated_timestamp"
	IS 'Last Updated Timestamp is the date and time the  record was last updated.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfnews"."published_incident_detail"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfnews"."published_incident_detail" ADD CONSTRAINT "pubincdtl_pk"
	PRIMARY KEY ("published_incident_detail_guid")
;

ALTER TABLE "wfnews"."published_incident_detail" ADD CONSTRAINT "pubincdtl_uk" UNIQUE ("incident_guid","news_created_timestamp")
;

/* Create Foreign Key Constraints */

ALTER TABLE "wfnews"."published_incident_detail" ADD CONSTRAINT "pubincdtl_pubstcd_fk"
	FOREIGN KEY ("news_publication_status_code") REFERENCES "wfnews"."news_publication_status_code" ("news_publication_status_code") ON DELETE No Action ON UPDATE No Action
;