version: '3.7'
services:
    wfone-pm-load-test:
                    build:
                        context: .
                        dockerfile: Dockerfile
                    ports:
                        - "8080:8080"