FROM apache/apisix-dashboard
EXPOSE 9000
COPY docker/apisix-gui-conf.yaml /usr/local/apisix-dashboard/conf/conf.yaml
USER root
RUN apt-get update &&\
  apt-get install -y nginx &&\
  sed -i 's/#!\/usr\/bin\/env bash/&\nnginx\&/' /docker-entrypoint.sh
COPY docker/default.conf /etc/nginx/conf.d/default.conf