FROM ubuntu:22.04
EXPOSE 8080
RUN apt-get update &&\
  apt-get -y install nginx &&\
  sed -i 's@#!\/usr\/bin\/env bash@&\nsed -i "s/{MAX_SIZE}/\$MAX_SIZE/" /etc/nginx/conf.d/default.conf\nsed -i "s/{API_KEY}/\$API_KEY/" /etc/nginx/conf.d/default.conf\nsed -i "s/{LICENSE_PLATE}/\$LICENSE_PLATE/" /etc/nginx/conf.d/default.conf\nsed -i "s/{TARGET_ENV}/\$TARGET_ENV/" /etc/nginx/conf.d/default.conf\nnginx\&@' /docker-entrypoint.sh &&\
  mkdir -p /var/cache/nginx && mkdir -p /var/log/nginx && mkdir -p /etc/nginx
RUN chmod 766 /var/cache/nginx && chmod 777 /var/run && chmod 766 /var/log && chmod -R 766 /etc/nginx && chmod -R 777 /var/lib/nginx && chmod 777 /tmp
COPY docker/default.conf /etc/nginx/conf.d/default.conf
VOLUME /var/cache/nginx /var/run /var/log /etc/nginx /var/lib/nginx /tmp
