#nginx is installed only because, when running as a service, we need a health check available
#The 'tail' command is used only to prevent the image from from constantly restarting
FROM liquibase/liquibase
ADD database /liquibase
EXPOSE 8080
USER root
RUN apt-get update &&\
  apt-get install -y nginx &&\
  echo '#!/bin/bash\nnginx\nliquibase update --changelogFile=$CHANGELOG_FOLDER/main-changelog.json --defaultsFile=/liquibase/liquibase.properties --log-file=/liquibase/liquibase.log --url=$DB_URL --username=$DB_USER --password=$DB_PASS\ntail -f /liquibase/liquibase.log' > /liquibase/docker-entrypoint.sh &&\
  mkdir -p /var/cache/nginx && mkdir -p /etc/nginx
RUN chmod 766 /var/cache/nginx && chmod 777 /var/run && chmod 766 -R /var/log && chmod -R 766 /etc/nginx && chmod -R 766 /liquibase && chmod 777 -R /var/lib/nginx
COPY docker/default_liquibase.conf /etc/nginx/conf.d/default.conf
VOLUME /var/cache/nginx /var/run /var/log /etc/nginx /var/lib/nginx /liquibase
