FROM registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
COPY contrib/.npmrc /home/jboss/
COPY contrib/settings.xml /opt/jboss/container/maven/default/jboss-settings.xml
#COPY contrib/settings-security.xml /home/jboss/.m2/