apiVersion: v1
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations: {}
    creationTimestamp: null
    labels:
      shared: "true"
    name: openjdk18-openshift
  spec:
    lookupPolicy:
      local: true
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: "registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:${IMAGE_TAG}"
      importPolicy: {}
      name: "${IMAGE_TAG}"
      referencePolicy:
        type: Local
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      shared: "true"
    name: base-openjdk18-openshift
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      build: base-openjdk18-openshift
    name: base-openjdk18-openshift
  spec:
    nodeSelector: null
    runPolicy: SerialLatestOnly
    completionDeadlineSeconds: 240 # 4 minutes
    output:
      to:
        kind: ImageStreamTag
        name: base-openjdk18-openshift:${IMAGE_TAG}
    postCommit: {}
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi
    source:
      binary: {}
      type: Binary
      contextDir: "docker/base-openjdk18-openshift"
    strategy:
      dockerStrategy:
        imageOptimizationPolicy: SkipLayers
        from:
          kind: ImageStreamTag
          name: openjdk18-openshift:${IMAGE_TAG}
      type: Docker
    triggers: {}
  status:
    lastVersion: 0
kind: Template
metadata: {}
parameters:
- name: IMAGE_TAG
  value: "1.6-23"