export const SCOPE_APPLICATION_PREFIX = 'WFIM.';
export const SCOPE_APPLICATION_PREFIX_NEWS = 'WFNEWS.';

// export const SCOPES_UI = {
//   CREATE_SIGN_UP:               `${SCOPE_APPLICATION_PREFIX}CREATE_ACCOUNT_REGISTRATION_REQUEST`,
//   DELETE_SIGN_UP:               `${SCOPE_APPLICATION_PREFIX}DELETE_ACCOUNT_REGISTRATION_REQUEST`, //*****
// }

export const ROLES_UI = {
  GENERAL_STAFF: `${SCOPE_APPLICATION_PREFIX}INCIDENT_GENERAL_STAFF`, //*****
  ADMIN: `${SCOPE_APPLICATION_PREFIX_NEWS}WFNEWS_PUBLISHER`, //*****
  IM_ADMIN: `${SCOPE_APPLICATION_PREFIX}WFNEWS_ADMIN` //*****
};
