export const SCOPE_APPLICATION_PREFIX = 'WFIM.';
export const SCOPE_APPLICATION_PREFIX_NEWS = 'WFNEWS.';

export const ROLES_UI = {
  GENERAL_STAFF: `${SCOPE_APPLICATION_PREFIX}INCIDENT_GENERAL_STAFF`, //*****
  ADMIN: `${SCOPE_APPLICATION_PREFIX_NEWS}WFNEWS_PUBLISHER`, //*****
  IM_ADMIN: `${SCOPE_APPLICATION_PREFIX}WFNEWS_ADMIN`, //*****
};
