/*
 * Wildfire Point ID REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.bc.gov.mof.wfpointid.rest.client.v1.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * GeographyResource
 */
public class GeographyResource {
  @SerializedName("errorCount")
  private Integer errorCount = null;

  @SerializedName("errorMsg")
  private String errorMsg = null;

  @SerializedName("errorDetail")
  private String errorDetail = null;

  @SerializedName("lat")
  private Double lat = null;

  @SerializedName("lon")
  private Double lon = null;

  @SerializedName("timestamp")
  private String timestamp = null;

  @SerializedName("fuelType")
  private String fuelType = null;

  @SerializedName("slope")
  private Integer slope = null;

  @SerializedName("aspect")
  private Integer aspect = null;

  @SerializedName("elevation")
  private Integer elevation = null;

  @SerializedName("mapsheet")
  private String mapsheet = null;

  @SerializedName("vegLabel")
  private String vegLabel = null;

  @SerializedName("bioGeoClimaticZone")
  private String bioGeoClimaticZone = null;

  public GeographyResource errorCount(Integer errorCount) {
    this.errorCount = errorCount;
    return this;
  }

   /**
   * Get errorCount
   * @return errorCount
  **/
  @ApiModelProperty(value = "")
  public Integer getErrorCount() {
    return errorCount;
  }

  public void setErrorCount(Integer errorCount) {
    this.errorCount = errorCount;
  }

  public GeographyResource errorMsg(String errorMsg) {
    this.errorMsg = errorMsg;
    return this;
  }

   /**
   * Get errorMsg
   * @return errorMsg
  **/
  @ApiModelProperty(value = "")
  public String getErrorMsg() {
    return errorMsg;
  }

  public void setErrorMsg(String errorMsg) {
    this.errorMsg = errorMsg;
  }

  public GeographyResource errorDetail(String errorDetail) {
    this.errorDetail = errorDetail;
    return this;
  }

   /**
   * Get errorDetail
   * @return errorDetail
  **/
  @ApiModelProperty(value = "")
  public String getErrorDetail() {
    return errorDetail;
  }

  public void setErrorDetail(String errorDetail) {
    this.errorDetail = errorDetail;
  }

  public GeographyResource lat(Double lat) {
    this.lat = lat;
    return this;
  }

   /**
   * Get lat
   * @return lat
  **/
  @ApiModelProperty(value = "")
  public Double getLat() {
    return lat;
  }

  public void setLat(Double lat) {
    this.lat = lat;
  }

  public GeographyResource lon(Double lon) {
    this.lon = lon;
    return this;
  }

   /**
   * Get lon
   * @return lon
  **/
  @ApiModelProperty(value = "")
  public Double getLon() {
    return lon;
  }

  public void setLon(Double lon) {
    this.lon = lon;
  }

  public GeographyResource timestamp(String timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @ApiModelProperty(value = "")
  public String getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(String timestamp) {
    this.timestamp = timestamp;
  }

  public GeographyResource fuelType(String fuelType) {
    this.fuelType = fuelType;
    return this;
  }

   /**
   * Get fuelType
   * @return fuelType
  **/
  @ApiModelProperty(value = "")
  public String getFuelType() {
    return fuelType;
  }

  public void setFuelType(String fuelType) {
    this.fuelType = fuelType;
  }

  public GeographyResource slope(Integer slope) {
    this.slope = slope;
    return this;
  }

   /**
   * Get slope
   * @return slope
  **/
  @ApiModelProperty(value = "")
  public Integer getSlope() {
    return slope;
  }

  public void setSlope(Integer slope) {
    this.slope = slope;
  }

  public GeographyResource aspect(Integer aspect) {
    this.aspect = aspect;
    return this;
  }

   /**
   * Get aspect
   * @return aspect
  **/
  @ApiModelProperty(value = "")
  public Integer getAspect() {
    return aspect;
  }

  public void setAspect(Integer aspect) {
    this.aspect = aspect;
  }

  public GeographyResource elevation(Integer elevation) {
    this.elevation = elevation;
    return this;
  }

   /**
   * Get elevation
   * @return elevation
  **/
  @ApiModelProperty(value = "")
  public Integer getElevation() {
    return elevation;
  }

  public void setElevation(Integer elevation) {
    this.elevation = elevation;
  }

  public GeographyResource mapsheet(String mapsheet) {
    this.mapsheet = mapsheet;
    return this;
  }

   /**
   * Get mapsheet
   * @return mapsheet
  **/
  @ApiModelProperty(value = "")
  public String getMapsheet() {
    return mapsheet;
  }

  public void setMapsheet(String mapsheet) {
    this.mapsheet = mapsheet;
  }

  public GeographyResource vegLabel(String vegLabel) {
    this.vegLabel = vegLabel;
    return this;
  }

   /**
   * Get vegLabel
   * @return vegLabel
  **/
  @ApiModelProperty(value = "")
  public String getVegLabel() {
    return vegLabel;
  }

  public void setVegLabel(String vegLabel) {
    this.vegLabel = vegLabel;
  }

  public GeographyResource bioGeoClimaticZone(String bioGeoClimaticZone) {
    this.bioGeoClimaticZone = bioGeoClimaticZone;
    return this;
  }

   /**
   * Get bioGeoClimaticZone
   * @return bioGeoClimaticZone
  **/
  @ApiModelProperty(value = "")
  public String getBioGeoClimaticZone() {
    return bioGeoClimaticZone;
  }

  public void setBioGeoClimaticZone(String bioGeoClimaticZone) {
    this.bioGeoClimaticZone = bioGeoClimaticZone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeographyResource geographyResource = (GeographyResource) o;
    return Objects.equals(this.errorCount, geographyResource.errorCount) &&
        Objects.equals(this.errorMsg, geographyResource.errorMsg) &&
        Objects.equals(this.errorDetail, geographyResource.errorDetail) &&
        Objects.equals(this.lat, geographyResource.lat) &&
        Objects.equals(this.lon, geographyResource.lon) &&
        Objects.equals(this.timestamp, geographyResource.timestamp) &&
        Objects.equals(this.fuelType, geographyResource.fuelType) &&
        Objects.equals(this.slope, geographyResource.slope) &&
        Objects.equals(this.aspect, geographyResource.aspect) &&
        Objects.equals(this.elevation, geographyResource.elevation) &&
        Objects.equals(this.mapsheet, geographyResource.mapsheet) &&
        Objects.equals(this.vegLabel, geographyResource.vegLabel) &&
        Objects.equals(this.bioGeoClimaticZone, geographyResource.bioGeoClimaticZone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorCount, errorMsg, errorDetail, lat, lon, timestamp, fuelType, slope, aspect, elevation, mapsheet, vegLabel, bioGeoClimaticZone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeographyResource {\n");
    
    sb.append("    errorCount: ").append(toIndentedString(errorCount)).append("\n");
    sb.append("    errorMsg: ").append(toIndentedString(errorMsg)).append("\n");
    sb.append("    errorDetail: ").append(toIndentedString(errorDetail)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    lon: ").append(toIndentedString(lon)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    fuelType: ").append(toIndentedString(fuelType)).append("\n");
    sb.append("    slope: ").append(toIndentedString(slope)).append("\n");
    sb.append("    aspect: ").append(toIndentedString(aspect)).append("\n");
    sb.append("    elevation: ").append(toIndentedString(elevation)).append("\n");
    sb.append("    mapsheet: ").append(toIndentedString(mapsheet)).append("\n");
    sb.append("    vegLabel: ").append(toIndentedString(vegLabel)).append("\n");
    sb.append("    bioGeoClimaticZone: ").append(toIndentedString(bioGeoClimaticZone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

