/*
 * Wildfire Point ID REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.bc.gov.mof.wfpointid.rest.client.v1.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * OwnershipResource
 */
public class OwnershipResource {
  @SerializedName("errorCount")
  private Integer errorCount = null;

  @SerializedName("errorMsg")
  private String errorMsg = null;

  @SerializedName("errorDetail")
  private String errorDetail = null;

  @SerializedName("lat")
  private Double lat = null;

  @SerializedName("lon")
  private Double lon = null;

  @SerializedName("timestamp")
  private String timestamp = null;

  @SerializedName("fireCentre")
  private String fireCentre = null;

  @SerializedName("fireZone")
  private String fireZone = null;

  @SerializedName("resourceDistrict")
  private String resourceDistrict = null;

  @SerializedName("pid")
  private String pid = null;

  @SerializedName("ownershipClass")
  private String ownershipClass = null;

  @SerializedName("protectedLand")
  private String protectedLand = null;

  @SerializedName("municipality")
  private String municipality = null;

  @SerializedName("regionalDistrict")
  private String regionalDistrict = null;

  @SerializedName("clientAssetAreaName")
  private String clientAssetAreaName = null;

  @SerializedName("clientAssetAreaType")
  private String clientAssetAreaType = null;

  @SerializedName("clientAssetAreaContact")
  private String clientAssetAreaContact = null;

  @SerializedName("clientAssetLineName")
  private String clientAssetLineName = null;

  @SerializedName("clientAssetLineType")
  private String clientAssetLineType = null;

  @SerializedName("clientAssetLineContact")
  private String clientAssetLineContact = null;

  @SerializedName("clientAssetPointName")
  private String clientAssetPointName = null;

  @SerializedName("clientAssetPointType")
  private String clientAssetPointType = null;

  @SerializedName("clientAssetPointContact")
  private String clientAssetPointContact = null;

  @SerializedName("tenureTFL")
  private String tenureTFL = null;

  @SerializedName("tenureManagedForest")
  private String tenureManagedForest = null;

  @SerializedName("fnReserve")
  private String fnReserve = null;

  @SerializedName("fnTitle")
  private String fnTitle = null;

  @SerializedName("watershed")
  private String watershed = null;

  @SerializedName("fireDept")
  private String fireDept = null;

  public OwnershipResource errorCount(Integer errorCount) {
    this.errorCount = errorCount;
    return this;
  }

   /**
   * Get errorCount
   * @return errorCount
  **/
  @ApiModelProperty(value = "")
  public Integer getErrorCount() {
    return errorCount;
  }

  public void setErrorCount(Integer errorCount) {
    this.errorCount = errorCount;
  }

  public OwnershipResource errorMsg(String errorMsg) {
    this.errorMsg = errorMsg;
    return this;
  }

   /**
   * Get errorMsg
   * @return errorMsg
  **/
  @ApiModelProperty(value = "")
  public String getErrorMsg() {
    return errorMsg;
  }

  public void setErrorMsg(String errorMsg) {
    this.errorMsg = errorMsg;
  }

  public OwnershipResource errorDetail(String errorDetail) {
    this.errorDetail = errorDetail;
    return this;
  }

   /**
   * Get errorDetail
   * @return errorDetail
  **/
  @ApiModelProperty(value = "")
  public String getErrorDetail() {
    return errorDetail;
  }

  public void setErrorDetail(String errorDetail) {
    this.errorDetail = errorDetail;
  }

  public OwnershipResource lat(Double lat) {
    this.lat = lat;
    return this;
  }

   /**
   * Get lat
   * @return lat
  **/
  @ApiModelProperty(value = "")
  public Double getLat() {
    return lat;
  }

  public void setLat(Double lat) {
    this.lat = lat;
  }

  public OwnershipResource lon(Double lon) {
    this.lon = lon;
    return this;
  }

   /**
   * Get lon
   * @return lon
  **/
  @ApiModelProperty(value = "")
  public Double getLon() {
    return lon;
  }

  public void setLon(Double lon) {
    this.lon = lon;
  }

  public OwnershipResource timestamp(String timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @ApiModelProperty(value = "")
  public String getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(String timestamp) {
    this.timestamp = timestamp;
  }

  public OwnershipResource fireCentre(String fireCentre) {
    this.fireCentre = fireCentre;
    return this;
  }

   /**
   * Get fireCentre
   * @return fireCentre
  **/
  @ApiModelProperty(value = "")
  public String getFireCentre() {
    return fireCentre;
  }

  public void setFireCentre(String fireCentre) {
    this.fireCentre = fireCentre;
  }

  public OwnershipResource fireZone(String fireZone) {
    this.fireZone = fireZone;
    return this;
  }

   /**
   * Get fireZone
   * @return fireZone
  **/
  @ApiModelProperty(value = "")
  public String getFireZone() {
    return fireZone;
  }

  public void setFireZone(String fireZone) {
    this.fireZone = fireZone;
  }

  public OwnershipResource resourceDistrict(String resourceDistrict) {
    this.resourceDistrict = resourceDistrict;
    return this;
  }

   /**
   * Get resourceDistrict
   * @return resourceDistrict
  **/
  @ApiModelProperty(value = "")
  public String getResourceDistrict() {
    return resourceDistrict;
  }

  public void setResourceDistrict(String resourceDistrict) {
    this.resourceDistrict = resourceDistrict;
  }

  public OwnershipResource pid(String pid) {
    this.pid = pid;
    return this;
  }

   /**
   * Get pid
   * @return pid
  **/
  @ApiModelProperty(value = "")
  public String getPid() {
    return pid;
  }

  public void setPid(String pid) {
    this.pid = pid;
  }

  public OwnershipResource ownershipClass(String ownershipClass) {
    this.ownershipClass = ownershipClass;
    return this;
  }

   /**
   * Get ownershipClass
   * @return ownershipClass
  **/
  @ApiModelProperty(value = "")
  public String getOwnershipClass() {
    return ownershipClass;
  }

  public void setOwnershipClass(String ownershipClass) {
    this.ownershipClass = ownershipClass;
  }

  public OwnershipResource protectedLand(String protectedLand) {
    this.protectedLand = protectedLand;
    return this;
  }

   /**
   * Get protectedLand
   * @return protectedLand
  **/
  @ApiModelProperty(value = "")
  public String getProtectedLand() {
    return protectedLand;
  }

  public void setProtectedLand(String protectedLand) {
    this.protectedLand = protectedLand;
  }

  public OwnershipResource municipality(String municipality) {
    this.municipality = municipality;
    return this;
  }

   /**
   * Get municipality
   * @return municipality
  **/
  @ApiModelProperty(value = "")
  public String getMunicipality() {
    return municipality;
  }

  public void setMunicipality(String municipality) {
    this.municipality = municipality;
  }

  public OwnershipResource regionalDistrict(String regionalDistrict) {
    this.regionalDistrict = regionalDistrict;
    return this;
  }

   /**
   * Get regionalDistrict
   * @return regionalDistrict
  **/
  @ApiModelProperty(value = "")
  public String getRegionalDistrict() {
    return regionalDistrict;
  }

  public void setRegionalDistrict(String regionalDistrict) {
    this.regionalDistrict = regionalDistrict;
  }

  public OwnershipResource clientAssetAreaName(String clientAssetAreaName) {
    this.clientAssetAreaName = clientAssetAreaName;
    return this;
  }

   /**
   * Get clientAssetAreaName
   * @return clientAssetAreaName
  **/
  @ApiModelProperty(value = "")
  public String getClientAssetAreaName() {
    return clientAssetAreaName;
  }

  public void setClientAssetAreaName(String clientAssetAreaName) {
    this.clientAssetAreaName = clientAssetAreaName;
  }

  public OwnershipResource clientAssetAreaType(String clientAssetAreaType) {
    this.clientAssetAreaType = clientAssetAreaType;
    return this;
  }

   /**
   * Get clientAssetAreaType
   * @return clientAssetAreaType
  **/
  @ApiModelProperty(value = "")
  public String getClientAssetAreaType() {
    return clientAssetAreaType;
  }

  public void setClientAssetAreaType(String clientAssetAreaType) {
    this.clientAssetAreaType = clientAssetAreaType;
  }

  public OwnershipResource clientAssetAreaContact(String clientAssetAreaContact) {
    this.clientAssetAreaContact = clientAssetAreaContact;
    return this;
  }

   /**
   * Get clientAssetAreaContact
   * @return clientAssetAreaContact
  **/
  @ApiModelProperty(value = "")
  public String getClientAssetAreaContact() {
    return clientAssetAreaContact;
  }

  public void setClientAssetAreaContact(String clientAssetAreaContact) {
    this.clientAssetAreaContact = clientAssetAreaContact;
  }

  public OwnershipResource clientAssetLineName(String clientAssetLineName) {
    this.clientAssetLineName = clientAssetLineName;
    return this;
  }

   /**
   * Get clientAssetLineName
   * @return clientAssetLineName
  **/
  @ApiModelProperty(value = "")
  public String getClientAssetLineName() {
    return clientAssetLineName;
  }

  public void setClientAssetLineName(String clientAssetLineName) {
    this.clientAssetLineName = clientAssetLineName;
  }

  public OwnershipResource clientAssetLineType(String clientAssetLineType) {
    this.clientAssetLineType = clientAssetLineType;
    return this;
  }

   /**
   * Get clientAssetLineType
   * @return clientAssetLineType
  **/
  @ApiModelProperty(value = "")
  public String getClientAssetLineType() {
    return clientAssetLineType;
  }

  public void setClientAssetLineType(String clientAssetLineType) {
    this.clientAssetLineType = clientAssetLineType;
  }

  public OwnershipResource clientAssetLineContact(String clientAssetLineContact) {
    this.clientAssetLineContact = clientAssetLineContact;
    return this;
  }

   /**
   * Get clientAssetLineContact
   * @return clientAssetLineContact
  **/
  @ApiModelProperty(value = "")
  public String getClientAssetLineContact() {
    return clientAssetLineContact;
  }

  public void setClientAssetLineContact(String clientAssetLineContact) {
    this.clientAssetLineContact = clientAssetLineContact;
  }

  public OwnershipResource clientAssetPointName(String clientAssetPointName) {
    this.clientAssetPointName = clientAssetPointName;
    return this;
  }

   /**
   * Get clientAssetPointName
   * @return clientAssetPointName
  **/
  @ApiModelProperty(value = "")
  public String getClientAssetPointName() {
    return clientAssetPointName;
  }

  public void setClientAssetPointName(String clientAssetPointName) {
    this.clientAssetPointName = clientAssetPointName;
  }

  public OwnershipResource clientAssetPointType(String clientAssetPointType) {
    this.clientAssetPointType = clientAssetPointType;
    return this;
  }

   /**
   * Get clientAssetPointType
   * @return clientAssetPointType
  **/
  @ApiModelProperty(value = "")
  public String getClientAssetPointType() {
    return clientAssetPointType;
  }

  public void setClientAssetPointType(String clientAssetPointType) {
    this.clientAssetPointType = clientAssetPointType;
  }

  public OwnershipResource clientAssetPointContact(String clientAssetPointContact) {
    this.clientAssetPointContact = clientAssetPointContact;
    return this;
  }

   /**
   * Get clientAssetPointContact
   * @return clientAssetPointContact
  **/
  @ApiModelProperty(value = "")
  public String getClientAssetPointContact() {
    return clientAssetPointContact;
  }

  public void setClientAssetPointContact(String clientAssetPointContact) {
    this.clientAssetPointContact = clientAssetPointContact;
  }

  public OwnershipResource tenureTFL(String tenureTFL) {
    this.tenureTFL = tenureTFL;
    return this;
  }

   /**
   * Get tenureTFL
   * @return tenureTFL
  **/
  @ApiModelProperty(value = "")
  public String getTenureTFL() {
    return tenureTFL;
  }

  public void setTenureTFL(String tenureTFL) {
    this.tenureTFL = tenureTFL;
  }

  public OwnershipResource tenureManagedForest(String tenureManagedForest) {
    this.tenureManagedForest = tenureManagedForest;
    return this;
  }

   /**
   * Get tenureManagedForest
   * @return tenureManagedForest
  **/
  @ApiModelProperty(value = "")
  public String getTenureManagedForest() {
    return tenureManagedForest;
  }

  public void setTenureManagedForest(String tenureManagedForest) {
    this.tenureManagedForest = tenureManagedForest;
  }

  public OwnershipResource fnReserve(String fnReserve) {
    this.fnReserve = fnReserve;
    return this;
  }

   /**
   * Get fnReserve
   * @return fnReserve
  **/
  @ApiModelProperty(value = "")
  public String getFnReserve() {
    return fnReserve;
  }

  public void setFnReserve(String fnReserve) {
    this.fnReserve = fnReserve;
  }

  public OwnershipResource fnTitle(String fnTitle) {
    this.fnTitle = fnTitle;
    return this;
  }

   /**
   * Get fnTitle
   * @return fnTitle
  **/
  @ApiModelProperty(value = "")
  public String getFnTitle() {
    return fnTitle;
  }

  public void setFnTitle(String fnTitle) {
    this.fnTitle = fnTitle;
  }

  public OwnershipResource watershed(String watershed) {
    this.watershed = watershed;
    return this;
  }

   /**
   * Get watershed
   * @return watershed
  **/
  @ApiModelProperty(value = "")
  public String getWatershed() {
    return watershed;
  }

  public void setWatershed(String watershed) {
    this.watershed = watershed;
  }

  public OwnershipResource fireDept(String fireDept) {
    this.fireDept = fireDept;
    return this;
  }

   /**
   * Get fireDept
   * @return fireDept
  **/
  @ApiModelProperty(value = "")
  public String getFireDept() {
    return fireDept;
  }

  public void setFireDept(String fireDept) {
    this.fireDept = fireDept;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OwnershipResource ownershipResource = (OwnershipResource) o;
    return Objects.equals(this.errorCount, ownershipResource.errorCount) &&
        Objects.equals(this.errorMsg, ownershipResource.errorMsg) &&
        Objects.equals(this.errorDetail, ownershipResource.errorDetail) &&
        Objects.equals(this.lat, ownershipResource.lat) &&
        Objects.equals(this.lon, ownershipResource.lon) &&
        Objects.equals(this.timestamp, ownershipResource.timestamp) &&
        Objects.equals(this.fireCentre, ownershipResource.fireCentre) &&
        Objects.equals(this.fireZone, ownershipResource.fireZone) &&
        Objects.equals(this.resourceDistrict, ownershipResource.resourceDistrict) &&
        Objects.equals(this.pid, ownershipResource.pid) &&
        Objects.equals(this.ownershipClass, ownershipResource.ownershipClass) &&
        Objects.equals(this.protectedLand, ownershipResource.protectedLand) &&
        Objects.equals(this.municipality, ownershipResource.municipality) &&
        Objects.equals(this.regionalDistrict, ownershipResource.regionalDistrict) &&
        Objects.equals(this.clientAssetAreaName, ownershipResource.clientAssetAreaName) &&
        Objects.equals(this.clientAssetAreaType, ownershipResource.clientAssetAreaType) &&
        Objects.equals(this.clientAssetAreaContact, ownershipResource.clientAssetAreaContact) &&
        Objects.equals(this.clientAssetLineName, ownershipResource.clientAssetLineName) &&
        Objects.equals(this.clientAssetLineType, ownershipResource.clientAssetLineType) &&
        Objects.equals(this.clientAssetLineContact, ownershipResource.clientAssetLineContact) &&
        Objects.equals(this.clientAssetPointName, ownershipResource.clientAssetPointName) &&
        Objects.equals(this.clientAssetPointType, ownershipResource.clientAssetPointType) &&
        Objects.equals(this.clientAssetPointContact, ownershipResource.clientAssetPointContact) &&
        Objects.equals(this.tenureTFL, ownershipResource.tenureTFL) &&
        Objects.equals(this.tenureManagedForest, ownershipResource.tenureManagedForest) &&
        Objects.equals(this.fnReserve, ownershipResource.fnReserve) &&
        Objects.equals(this.fnTitle, ownershipResource.fnTitle) &&
        Objects.equals(this.watershed, ownershipResource.watershed) &&
        Objects.equals(this.fireDept, ownershipResource.fireDept);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorCount, errorMsg, errorDetail, lat, lon, timestamp, fireCentre, fireZone, resourceDistrict, pid, ownershipClass, protectedLand, municipality, regionalDistrict, clientAssetAreaName, clientAssetAreaType, clientAssetAreaContact, clientAssetLineName, clientAssetLineType, clientAssetLineContact, clientAssetPointName, clientAssetPointType, clientAssetPointContact, tenureTFL, tenureManagedForest, fnReserve, fnTitle, watershed, fireDept);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OwnershipResource {\n");
    
    sb.append("    errorCount: ").append(toIndentedString(errorCount)).append("\n");
    sb.append("    errorMsg: ").append(toIndentedString(errorMsg)).append("\n");
    sb.append("    errorDetail: ").append(toIndentedString(errorDetail)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    lon: ").append(toIndentedString(lon)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    fireCentre: ").append(toIndentedString(fireCentre)).append("\n");
    sb.append("    fireZone: ").append(toIndentedString(fireZone)).append("\n");
    sb.append("    resourceDistrict: ").append(toIndentedString(resourceDistrict)).append("\n");
    sb.append("    pid: ").append(toIndentedString(pid)).append("\n");
    sb.append("    ownershipClass: ").append(toIndentedString(ownershipClass)).append("\n");
    sb.append("    protectedLand: ").append(toIndentedString(protectedLand)).append("\n");
    sb.append("    municipality: ").append(toIndentedString(municipality)).append("\n");
    sb.append("    regionalDistrict: ").append(toIndentedString(regionalDistrict)).append("\n");
    sb.append("    clientAssetAreaName: ").append(toIndentedString(clientAssetAreaName)).append("\n");
    sb.append("    clientAssetAreaType: ").append(toIndentedString(clientAssetAreaType)).append("\n");
    sb.append("    clientAssetAreaContact: ").append(toIndentedString(clientAssetAreaContact)).append("\n");
    sb.append("    clientAssetLineName: ").append(toIndentedString(clientAssetLineName)).append("\n");
    sb.append("    clientAssetLineType: ").append(toIndentedString(clientAssetLineType)).append("\n");
    sb.append("    clientAssetLineContact: ").append(toIndentedString(clientAssetLineContact)).append("\n");
    sb.append("    clientAssetPointName: ").append(toIndentedString(clientAssetPointName)).append("\n");
    sb.append("    clientAssetPointType: ").append(toIndentedString(clientAssetPointType)).append("\n");
    sb.append("    clientAssetPointContact: ").append(toIndentedString(clientAssetPointContact)).append("\n");
    sb.append("    tenureTFL: ").append(toIndentedString(tenureTFL)).append("\n");
    sb.append("    tenureManagedForest: ").append(toIndentedString(tenureManagedForest)).append("\n");
    sb.append("    fnReserve: ").append(toIndentedString(fnReserve)).append("\n");
    sb.append("    fnTitle: ").append(toIndentedString(fnTitle)).append("\n");
    sb.append("    watershed: ").append(toIndentedString(watershed)).append("\n");
    sb.append("    fireDept: ").append(toIndentedString(fireDept)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

