/*
 * Wildfire Point ID REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.bc.gov.mof.wfpointid.rest.client.v1.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * WeatherDaily
 */
public class WeatherDaily {
  @SerializedName("day")
  private String day = null;

  @SerializedName("index")
  private Integer index = null;

  @SerializedName("forecastInd")
  private Boolean forecastInd = Boolean.FALSE;

  @SerializedName("temp")
  private Double temp = null;

  @SerializedName("relativeHumidity")
  private Integer relativeHumidity = null;

  @SerializedName("windSpeed")
  private Double windSpeed = null;

  @SerializedName("windDirection")
  private Integer windDirection = null;

  @SerializedName("windCardinalDir")
  private String windCardinalDir = null;

  @SerializedName("precipitation")
  private Double precipitation = null;

  @SerializedName("buildupIndex")
  private Double buildupIndex = null;

  @SerializedName("droughtCode")
  private Double droughtCode = null;

  @SerializedName("duffMoistureCode")
  private Double duffMoistureCode = null;

  @SerializedName("fineFuelMoistureCode")
  private Double fineFuelMoistureCode = null;

  @SerializedName("initialSpreadIndex")
  private Double initialSpreadIndex = null;

  @SerializedName("fireWeatherIndex")
  private Double fireWeatherIndex = null;

  public WeatherDaily day(String day) {
    this.day = day;
    return this;
  }

   /**
   * Get day
   * @return day
  **/
  @ApiModelProperty(value = "")
  public String getDay() {
    return day;
  }

  public void setDay(String day) {
    this.day = day;
  }

  public WeatherDaily index(Integer index) {
    this.index = index;
    return this;
  }

   /**
   * Get index
   * @return index
  **/
  @ApiModelProperty(value = "")
  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }

  public WeatherDaily forecastInd(Boolean forecastInd) {
    this.forecastInd = forecastInd;
    return this;
  }

   /**
   * Get forecastInd
   * @return forecastInd
  **/
  @ApiModelProperty(value = "")
  public Boolean isForecastInd() {
    return forecastInd;
  }

  public void setForecastInd(Boolean forecastInd) {
    this.forecastInd = forecastInd;
  }

  public WeatherDaily temp(Double temp) {
    this.temp = temp;
    return this;
  }

   /**
   * Get temp
   * @return temp
  **/
  @ApiModelProperty(value = "")
  public Double getTemp() {
    return temp;
  }

  public void setTemp(Double temp) {
    this.temp = temp;
  }

  public WeatherDaily relativeHumidity(Integer relativeHumidity) {
    this.relativeHumidity = relativeHumidity;
    return this;
  }

   /**
   * Get relativeHumidity
   * @return relativeHumidity
  **/
  @ApiModelProperty(value = "")
  public Integer getRelativeHumidity() {
    return relativeHumidity;
  }

  public void setRelativeHumidity(Integer relativeHumidity) {
    this.relativeHumidity = relativeHumidity;
  }

  public WeatherDaily windSpeed(Double windSpeed) {
    this.windSpeed = windSpeed;
    return this;
  }

   /**
   * Get windSpeed
   * @return windSpeed
  **/
  @ApiModelProperty(value = "")
  public Double getWindSpeed() {
    return windSpeed;
  }

  public void setWindSpeed(Double windSpeed) {
    this.windSpeed = windSpeed;
  }

  public WeatherDaily windDirection(Integer windDirection) {
    this.windDirection = windDirection;
    return this;
  }

   /**
   * Get windDirection
   * @return windDirection
  **/
  @ApiModelProperty(value = "")
  public Integer getWindDirection() {
    return windDirection;
  }

  public void setWindDirection(Integer windDirection) {
    this.windDirection = windDirection;
  }

  public WeatherDaily windCardinalDir(String windCardinalDir) {
    this.windCardinalDir = windCardinalDir;
    return this;
  }

   /**
   * Get windCardinalDir
   * @return windCardinalDir
  **/
  @ApiModelProperty(value = "")
  public String getWindCardinalDir() {
    return windCardinalDir;
  }

  public void setWindCardinalDir(String windCardinalDir) {
    this.windCardinalDir = windCardinalDir;
  }

  public WeatherDaily precipitation(Double precipitation) {
    this.precipitation = precipitation;
    return this;
  }

   /**
   * Get precipitation
   * @return precipitation
  **/
  @ApiModelProperty(value = "")
  public Double getPrecipitation() {
    return precipitation;
  }

  public void setPrecipitation(Double precipitation) {
    this.precipitation = precipitation;
  }

  public WeatherDaily buildupIndex(Double buildupIndex) {
    this.buildupIndex = buildupIndex;
    return this;
  }

   /**
   * Get buildupIndex
   * @return buildupIndex
  **/
  @ApiModelProperty(value = "")
  public Double getBuildupIndex() {
    return buildupIndex;
  }

  public void setBuildupIndex(Double buildupIndex) {
    this.buildupIndex = buildupIndex;
  }


  public WeatherDaily droughtCode(Double droughtCode) {
    this.droughtCode = droughtCode;
    return this;
  }

   /**
   * Get droughtCode
   * @return droughtCode
  **/
  @ApiModelProperty(value = "")
  public Double getDroughtCode() {
    return droughtCode;
  }

  public void setDroughtCode(Double droughtCode) {
    this.droughtCode = droughtCode;
  }

  public WeatherDaily duffMoistureCode(Double duffMoistureCode) {
    this.duffMoistureCode = duffMoistureCode;
    return this;
  }

   /**
   * Get duffMoistureCode
   * @return duffMoistureCode
  **/
  @ApiModelProperty(value = "")
  public Double getDuffMoistureCode() {
    return duffMoistureCode;
  }

  public void setDuffMoistureCode(Double duffMoistureCode) {
    this.duffMoistureCode = duffMoistureCode;
  }

  public WeatherDaily fineFuelMoistureCode(Double fineFuelMoistureCode) {
    this.fineFuelMoistureCode = fineFuelMoistureCode;
    return this;
  }

   /**
   * Get fineFuelMoistureCode
   * @return fineFuelMoistureCode
  **/
  @ApiModelProperty(value = "")
  public Double getFineFuelMoistureCode() {
    return fineFuelMoistureCode;
  }

  public void setFineFuelMoistureCode(Double fineFuelMoistureCode) {
    this.fineFuelMoistureCode = fineFuelMoistureCode;
  }

  public WeatherDaily initialSpreadIndex(Double initialSpreadIndex) {
    this.initialSpreadIndex = initialSpreadIndex;
    return this;
  }

   /**
   * Get initialSpreadIndex
   * @return initialSpreadIndex
  **/
  @ApiModelProperty(value = "")
  public Double getInitialSpreadIndex() {
    return initialSpreadIndex;
  }

  public void setInitialSpreadIndex(Double initialSpreadIndex) {
    this.initialSpreadIndex = initialSpreadIndex;
  }

  public WeatherDaily fireWeatherIndex(Double fireWeatherIndex) {
    this.fireWeatherIndex = fireWeatherIndex;
    return this;
  }

   /**
   * Get fireWeatherIndex
   * @return fireWeatherIndex
  **/
  @ApiModelProperty(value = "")
  public Double getFireWeatherIndex() {
    return fireWeatherIndex;
  }

  public void setFireWeatherIndex(Double fireWeatherIndex) {
    this.fireWeatherIndex = fireWeatherIndex;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WeatherDaily weatherDaily = (WeatherDaily) o;
    return Objects.equals(this.day, weatherDaily.day) &&
        Objects.equals(this.index, weatherDaily.index) &&
        Objects.equals(this.forecastInd, weatherDaily.forecastInd) &&
        Objects.equals(this.temp, weatherDaily.temp) &&
        Objects.equals(this.relativeHumidity, weatherDaily.relativeHumidity) &&
        Objects.equals(this.windSpeed, weatherDaily.windSpeed) &&
        Objects.equals(this.windDirection, weatherDaily.windDirection) &&
        Objects.equals(this.windCardinalDir, weatherDaily.windCardinalDir) &&
        Objects.equals(this.precipitation, weatherDaily.precipitation) &&
        Objects.equals(this.buildupIndex, weatherDaily.buildupIndex) &&
        Objects.equals(this.droughtCode, weatherDaily.droughtCode) &&
        Objects.equals(this.duffMoistureCode, weatherDaily.duffMoistureCode) &&
        Objects.equals(this.fineFuelMoistureCode, weatherDaily.fineFuelMoistureCode) &&
        Objects.equals(this.initialSpreadIndex, weatherDaily.initialSpreadIndex) &&
        Objects.equals(this.fireWeatherIndex, weatherDaily.fireWeatherIndex);
  }

  @Override
  public int hashCode() {
    return Objects.hash(day, index, forecastInd, temp, relativeHumidity, windSpeed, windDirection, windCardinalDir, precipitation, buildupIndex, fineFuelMoistureCode, initialSpreadIndex, fireWeatherIndex);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WeatherDaily {\n");
    
    sb.append("    day: ").append(toIndentedString(day)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    forecastInd: ").append(toIndentedString(forecastInd)).append("\n");
    sb.append("    temp: ").append(toIndentedString(temp)).append("\n");
    sb.append("    relativeHumidity: ").append(toIndentedString(relativeHumidity)).append("\n");
    sb.append("    windSpeed: ").append(toIndentedString(windSpeed)).append("\n");
    sb.append("    windDirection: ").append(toIndentedString(windDirection)).append("\n");
    sb.append("    windCardinalDir: ").append(toIndentedString(windCardinalDir)).append("\n");
    sb.append("    precipitation: ").append(toIndentedString(precipitation)).append("\n");
    sb.append("    buildupIndex: ").append(toIndentedString(buildupIndex)).append("\n");
    sb.append("    droughtCode: ").append(toIndentedString(droughtCode)).append("\n");
    sb.append("    duffMoistureCode: ").append(toIndentedString(duffMoistureCode)).append("\n");
    sb.append("    fineFuelMoistureCode: ").append(toIndentedString(fineFuelMoistureCode)).append("\n");
    sb.append("    initialSpreadIndex: ").append(toIndentedString(initialSpreadIndex)).append("\n");
    sb.append("    fireWeatherIndex: ").append(toIndentedString(fireWeatherIndex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

