/*
 * Wildfire Point ID REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.bc.gov.mof.wfpointid.rest.client.v1.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * WeatherStation
 */
public class WeatherStation {
  @SerializedName("stationCode")
  private Integer stationCode = null;

  @SerializedName("stationName")
  private String stationName = null;

  @SerializedName("lat")
  private Double lat = null;

  @SerializedName("lon")
  private Double lon = null;

  @SerializedName("elevation")
  private Integer elevation = null;

  @SerializedName("hourly")
  private List<WeatherHourly> hourly = null;

  @SerializedName("daily")
  private List<WeatherDaily> daily = null;

  public WeatherStation stationCode(Integer stationCode) {
    this.stationCode = stationCode;
    return this;
  }

   /**
   * Get stationCode
   * @return stationCode
  **/
  @ApiModelProperty(value = "")
  public Integer getStationCode() {
    return stationCode;
  }

  public void setStationCode(Integer stationCode) {
    this.stationCode = stationCode;
  }

  public WeatherStation stationName(String stationName) {
    this.stationName = stationName;
    return this;
  }

   /**
   * Get stationName
   * @return stationName
  **/
  @ApiModelProperty(value = "")
  public String getStationName() {
    return stationName;
  }

  public void setStationName(String stationName) {
    this.stationName = stationName;
  }

  public WeatherStation lat(Double lat) {
    this.lat = lat;
    return this;
  }

   /**
   * Get lat
   * @return lat
  **/
  @ApiModelProperty(value = "")
  public Double getLat() {
    return lat;
  }

  public void setLat(Double lat) {
    this.lat = lat;
  }

  public WeatherStation lon(Double lon) {
    this.lon = lon;
    return this;
  }

   /**
   * Get lon
   * @return lon
  **/
  @ApiModelProperty(value = "")
  public Double getLon() {
    return lon;
  }

  public void setLon(Double lon) {
    this.lon = lon;
  }

  public WeatherStation elevation(Integer elevation) {
    this.elevation = elevation;
    return this;
  }

   /**
   * Get elevation
   * @return elevation
  **/
  @ApiModelProperty(value = "")
  public Integer getElevation() {
    return elevation;
  }

  public void setElevation(Integer elevation) {
    this.elevation = elevation;
  }

  public WeatherStation hourly(List<WeatherHourly> hourly) {
    this.hourly = hourly;
    return this;
  }

  public WeatherStation addHourlyItem(WeatherHourly hourlyItem) {
    if (this.hourly == null) {
      this.hourly = new ArrayList<WeatherHourly>();
    }
    this.hourly.add(hourlyItem);
    return this;
  }

   /**
   * Get hourly
   * @return hourly
  **/
  @ApiModelProperty(value = "")
  public List<WeatherHourly> getHourly() {
    return hourly;
  }

  public void setHourly(List<WeatherHourly> hourly) {
    this.hourly = hourly;
  }

  public WeatherStation daily(List<WeatherDaily> daily) {
    this.daily = daily;
    return this;
  }

  public WeatherStation addDailyItem(WeatherDaily dailyItem) {
    if (this.daily == null) {
      this.daily = new ArrayList<WeatherDaily>();
    }
    this.daily.add(dailyItem);
    return this;
  }

   /**
   * Get daily
   * @return daily
  **/
  @ApiModelProperty(value = "")
  public List<WeatherDaily> getDaily() {
    return daily;
  }

  public void setDaily(List<WeatherDaily> daily) {
    this.daily = daily;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WeatherStation weatherStation = (WeatherStation) o;
    return Objects.equals(this.stationCode, weatherStation.stationCode) &&
        Objects.equals(this.stationName, weatherStation.stationName) &&
        Objects.equals(this.lat, weatherStation.lat) &&
        Objects.equals(this.lon, weatherStation.lon) &&
        Objects.equals(this.elevation, weatherStation.elevation) &&
        Objects.equals(this.hourly, weatherStation.hourly) &&
        Objects.equals(this.daily, weatherStation.daily);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stationCode, stationName, lat, lon, elevation, hourly, daily);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WeatherStation {\n");
    
    sb.append("    stationCode: ").append(toIndentedString(stationCode)).append("\n");
    sb.append("    stationName: ").append(toIndentedString(stationName)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    lon: ").append(toIndentedString(lon)).append("\n");
    sb.append("    elevation: ").append(toIndentedString(elevation)).append("\n");
    sb.append("    hourly: ").append(toIndentedString(hourly)).append("\n");
    sb.append("    daily: ").append(toIndentedString(daily)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

