/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0    */
/*  Created On : 24-Jun-2022 11:02:21 AM        */
/*  DBMS       : PostgreSQL             */
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfnews"."related_file_attach_xref"
(
  "related_file_attach_xref_guid" VARCHAR(36) NOT NULL,    -- RELATED_FILE_ATTACH_XREF_GUID is a unique identifier for the record.
  "parent_file_attachment_guid" VARCHAR(36) NOT NULL,    -- PARENT_FILE_ATTACHMENT_GUID: Is a foreign key to FILE_ATTACHMENT: File Attachment is used to track file attachments for the wildfire application.   The File Attachment  table allows for attachments to be linked to various business objects in the system by mapping a file attachment to the ID of the Source Object and the Source Object Name Code.   This table will hold a document path, a foreign key to the Source Object Name table and an ID of the Source Object that owns the attachment. This will bring together the document path with the object that owns it and the table where the object is located.
  "child_file_attachment_guid" VARCHAR(36) NOT NULL,    -- CHILD_FILE_ATTACHMENT_GUID: Is a foreign key to FILE_ATTACHMENT: File Attachment is used to track file attachments for the wildfire application.   The File Attachment  table allows for attachments to be linked to various business objects in the system by mapping a file attachment to the ID of the Source Object and the Source Object Name Code.   This table will hold a document path, a foreign key to the Source Object Name table and an ID of the Source Object that owns the attachment. This will bring together the document path with the object that owns it and the table where the object is located.
  "revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
  "create_user" varchar(64)  NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
  "create_date" timestamp NOT NULL DEFAULT current_date,    -- CREATE_DATE is the date and time the row of data was created.
  "update_user" varchar(64)  NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
  "update_date" timestamp NOT NULL DEFAULT current_date    -- UPDATE_DATE is the date and time the row of data was updated.
)
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "wfnews"."related_file_attach_xref"
  IS 'Related File Attachment Xref is used to map file attachments that are related to each other.   An example, is a photo file attachment may have multiple thumbnail files of different resolutions related to the photo file.'
;

COMMENT ON COLUMN "wfnews"."related_file_attach_xref"."related_file_attach_xref_guid"
  IS 'RELATED_FILE_ATTACH_XREF_GUID is a unique identifier for the record.'
;

COMMENT ON COLUMN "wfnews"."related_file_attach_xref"."parent_file_attachment_guid"
  IS 'PARENT_FILE_ATTACHMENT_GUID: Is a foreign key to FILE_ATTACHMENT: File Attachment is used to track file attachments for the wildfire application.   The File Attachment  table allows for attachments to be linked to various business objects in the system by mapping a file attachment to the ID of the Source Object and the Source Object Name Code.   This table will hold a document path, a foreign key to the Source Object Name table and an ID of the Source Object that owns the attachment. This will bring together the document path with the object that owns it and the table where the object is located.'
;

COMMENT ON COLUMN "wfnews"."related_file_attach_xref"."child_file_attachment_guid"
  IS 'CHILD_FILE_ATTACHMENT_GUID: Is a foreign key to FILE_ATTACHMENT: File Attachment is used to track file attachments for the wildfire application.   The File Attachment  table allows for attachments to be linked to various business objects in the system by mapping a file attachment to the ID of the Source Object and the Source Object Name Code.   This table will hold a document path, a foreign key to the Source Object Name table and an ID of the Source Object that owns the attachment. This will bring together the document path with the object that owns it and the table where the object is located.'
;

COMMENT ON COLUMN "wfnews"."related_file_attach_xref"."revision_count"
  IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfnews"."related_file_attach_xref"."create_user"
  IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfnews"."related_file_attach_xref"."create_date"
  IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfnews"."related_file_attach_xref"."update_user"
  IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfnews"."related_file_attach_xref"."update_date"
  IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfnews"."related_file_attach_xref" ADD CONSTRAINT "rfax_pk"
  PRIMARY KEY ("related_file_attach_xref_guid")
;

ALTER TABLE "wfnews"."related_file_attach_xref" ADD CONSTRAINT "rfax_uk" UNIQUE ("parent_file_attachment_guid","child_file_attachment_guid")
;

CREATE INDEX "rfax_flattch_parent_idx" ON "wfnews"."related_file_attach_xref" ("parent_file_attachment_guid" ASC)
;

CREATE INDEX "rfax_flattch_child_idx" ON "wfnews"."related_file_attach_xref" ("child_file_attachment_guid" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "wfnews"."related_file_attach_xref" ADD CONSTRAINT "rfax_flattch_parent_fk"
  FOREIGN KEY ("parent_file_attachment_guid") REFERENCES "wfnews"."file_attachment" ("file_attachment_guid") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "wfnews"."related_file_attach_xref" ADD CONSTRAINT "rfax_flattch_child_fk"
  FOREIGN KEY ("child_file_attachment_guid") REFERENCES "wfnews"."file_attachment" ("file_attachment_guid") ON DELETE No Action ON UPDATE No Action
;