/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0    */
/*  Created On : 24-Jun-2022 11:02:32 AM        */
/*  DBMS       : PostgreSQL             */
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfnews"."file_attachment_metadata"
(
  "file_attachment_metadata_guid" VARCHAR(36) NOT NULL,    -- FILE_ATTACHMENT_METADATA_GUID is a unique identifier for the record.
  "file_attachment_guid" VARCHAR(36) NOT NULL,    -- FILE_ATTACHMENT_GUID: Is a foreign key to FILE_ATTACHMENT: File Attachment is used to track file attachments for the wildfire application.   The File Attachment  table allows for attachments to be linked to various business objects in the system by mapping a file attachment to the ID of the Source Object and the Source Object Name Code.   This table will hold a document path, a foreign key to the Source Object Name table and an ID of the Source Object that owns the attachment. This will bring together the document path with the object that owns it and the table where the object is located.
  "latitude" decimal(8,6) NULL,    -- Latitude is the geographic coordinate, in decimal degrees (dd.dddddd), of the location of the file attachment as measured from the equator, e.g., 55.323653.
  "longitude" decimal(9,6) NULL,    -- Longitude is the geographic coordinate, in decimal degrees (-ddd.dddddd), of the location of the  file attachment as measured from the prime meridian, e.g., -123.093544.
  "geometry" geometry(Point, 4326) NULL,    -- Geometry is the geographic point where the fire is suspected to have ignited. 
  "elevation_m" decimal(10,4) NULL,    -- Elevation M is the elevation in metres.
  "elevation_angle" decimal(6,3) NULL,    -- Elevation Angle is the angle up and down relative to the horizontal plane
  "azimuth" decimal(6,3) NULL,    -- Azimuth is an arc of the horizon measured between a fixed point (such as true north) and the vertical circle passing through the center of an object usually in astronomy and navigation clockwise from the north point through 360 degrees.
  "image_height" decimal(10) NULL,    -- Image Height defines the height of an image as a count of image pixels.
  "image_width" decimal(10) NULL,    -- Image Width defines the width of an image as a count of image pixels.
  "revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
  "create_user" varchar(64)  NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
  "create_date" timestamp NOT NULL DEFAULT current_date,    -- CREATE_DATE is the date and time the row of data was created.
  "update_user" varchar(64)  NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
  "update_date" timestamp NOT NULL DEFAULT current_date    -- UPDATE_DATE is the date and time the row of data was updated.
)
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "wfnews"."file_attachment_metadata"
  IS 'File Attachment Metadata is used to record metadata about a file attachment. For example, photo attachments will record spatial information about where the photo was taken.'
;

COMMENT ON COLUMN "wfnews"."file_attachment_metadata"."file_attachment_metadata_guid"
  IS 'FILE_ATTACHMENT_METADATA_GUID is a unique identifier for the record.'
;

COMMENT ON COLUMN "wfnews"."file_attachment_metadata"."file_attachment_guid"
  IS 'FILE_ATTACHMENT_GUID: Is a foreign key to FILE_ATTACHMENT: File Attachment is used to track file attachments for the wildfire application.   The File Attachment  table allows for attachments to be linked to various business objects in the system by mapping a file attachment to the ID of the Source Object and the Source Object Name Code.   This table will hold a document path, a foreign key to the Source Object Name table and an ID of the Source Object that owns the attachment. This will bring together the document path with the object that owns it and the table where the object is located.'
;

COMMENT ON COLUMN "wfnews"."file_attachment_metadata"."latitude"
  IS 'Latitude is the geographic coordinate, in decimal degrees (dd.dddddd), of the location of the file attachment as measured from the equator, e.g., 55.323653.'
;

COMMENT ON COLUMN "wfnews"."file_attachment_metadata"."longitude"
  IS 'Longitude is the geographic coordinate, in decimal degrees (-ddd.dddddd), of the location of the  file attachment as measured from the prime meridian, e.g., -123.093544.'
;

COMMENT ON COLUMN "wfnews"."file_attachment_metadata"."geometry"
  IS 'Geometry is the geographic point where the fire is suspected to have ignited. '
;

COMMENT ON COLUMN "wfnews"."file_attachment_metadata"."elevation_m"
  IS 'Elevation M is the elevation in metres.'
;

COMMENT ON COLUMN "wfnews"."file_attachment_metadata"."elevation_angle"
  IS 'Elevation Angle is the angle up and down relative to the horizontal plane'
;

COMMENT ON COLUMN "wfnews"."file_attachment_metadata"."azimuth"
  IS 'Azimuth is an arc of the horizon measured between a fixed point (such as true north) and the vertical circle passing through the center of an object usually in astronomy and navigation clockwise from the north point through 360 degrees.'
;

COMMENT ON COLUMN "wfnews"."file_attachment_metadata"."image_height"
  IS 'Image Height defines the height of an image as a count of image pixels.'
;

COMMENT ON COLUMN "wfnews"."file_attachment_metadata"."image_width"
  IS 'Image Width defines the width of an image as a count of image pixels.'
;

COMMENT ON COLUMN "wfnews"."file_attachment_metadata"."revision_count"
  IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfnews"."file_attachment_metadata"."create_user"
  IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfnews"."file_attachment_metadata"."create_date"
  IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfnews"."file_attachment_metadata"."update_user"
  IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfnews"."file_attachment_metadata"."update_date"
  IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfnews"."file_attachment_metadata" ADD CONSTRAINT "fatmd_pk"
  PRIMARY KEY ("file_attachment_metadata_guid")
;

ALTER TABLE "wfnews"."file_attachment_metadata" ADD CONSTRAINT "fatmd_uk" UNIQUE ("file_attachment_guid")
;

CREATE INDEX "fatmd_flattch_idx" ON "wfnews"."file_attachment_metadata" ("file_attachment_guid" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "wfnews"."file_attachment_metadata" ADD CONSTRAINT "fatmd_flattch_fk"
  FOREIGN KEY ("file_attachment_guid") REFERENCES "wfnews"."file_attachment" ("file_attachment_guid") ON DELETE No Action ON UPDATE No Action
;


--Create index based on point geometry
CREATE INDEX fatmd_point_geom_idx ON wfnews.file_attachment_metadata USING gist(geometry); 