/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0    */
/*  Created On : 24-Jun-2022 11:02:10 AM        */
/*  DBMS       : PostgreSQL             */
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfnews"."file_attachment_sequence"
(
  "file_attachment_sequence_guid" VARCHAR(36) NOT NULL,    -- FILE_ATTACHMENT_SEQUENCE_GUID is a unique identifier for the record.
  "source_object_name_code" varchar(10)  NOT NULL,    -- SOURCE_OBJECT_NAME_CODE: Is a foreign key to SOURCE_OBJECT_NAME_CODE: Source Object Name Code is a table to hold the name of the source object class that the attachment belongs to. Visually, the source object class is usually exposed via a user interface screen, so you can think of attachments being associated to a screen.  For instance, when an incident photo is attached to an incident, the code value in this table will be Incident, and the attachment would be viewable in the UI via the Incident page.   Current values: * Article
  "source_object_unique_id" varchar(50)  NOT NULL,    -- Source Object Unique Identifier is the actual primary key value of the source object that owns the attachment. This, along with the Source Object Name will fully identify what the attachment belongs to. With including future source object types, we don't know if the ID of future objects is going to be of type number, string or some other data type. In order to accommodate any date type, this column is of type string.
  "file_attachment_sequence" decimal(10) NOT NULL DEFAULT 0,    -- File Attachment Sequence contains the most current sequence value used by file attachments for a source object.
  "revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
  "create_user" varchar(64)  NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
  "create_date" timestamp NOT NULL DEFAULT current_date,    -- CREATE_DATE is the date and time the row of data was created.
  "update_user" varchar(64)  NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
  "update_date" timestamp NOT NULL DEFAULT current_date    -- UPDATE_DATE is the date and time the row of data was updated.
)
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "wfnews"."file_attachment_sequence"
  IS 'File Attachment Sequence is used to track a sequence number used for file attachments for a source object.  So if there is an Incident record and it has 4 photo attachments, the system needs to be able to identify photo 1, photo 2, ..., photo 4, and it needs to know what the next photo in the sequence should be (photo 5). This table will track the sequence value and allow the system to increment the sequence when a new attachment like a photo is added.'
;

COMMENT ON COLUMN "wfnews"."file_attachment_sequence"."file_attachment_sequence_guid"
  IS 'FILE_ATTACHMENT_SEQUENCE_GUID is a unique identifier for the record.'
;

COMMENT ON COLUMN "wfnews"."file_attachment_sequence"."source_object_name_code"
  IS 'SOURCE_OBJECT_NAME_CODE: Is a foreign key to SOURCE_OBJECT_NAME_CODE: Source Object Name Code is a table to hold the name of the source object class that the attachment belongs to. Visually, the source object class is usually exposed via a user interface screen, so you can think of attachments being associated to a screen.  For instance, when an incident photo is attached to an incident, the code value in this table will be Incident, and the attachment would be viewable in the UI via the Incident page.   Current values: * Article'
;

COMMENT ON COLUMN "wfnews"."file_attachment_sequence"."source_object_unique_id"
  IS 'Source Object Unique Identifier is the actual primary key value of the source object that owns the attachment. This, along with the Source Object Name will fully identify what the attachment belongs to. With including future source object types, we don''t know if the ID of future objects is going to be of type number, string or some other data type. In order to accommodate any date type, this column is of type string.'
;

COMMENT ON COLUMN "wfnews"."file_attachment_sequence"."file_attachment_sequence"
  IS 'File Attachment Sequence contains the most current sequence value used by file attachments for a source object.'
;

COMMENT ON COLUMN "wfnews"."file_attachment_sequence"."revision_count"
  IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfnews"."file_attachment_sequence"."create_user"
  IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfnews"."file_attachment_sequence"."create_date"
  IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfnews"."file_attachment_sequence"."update_user"
  IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfnews"."file_attachment_sequence"."update_date"
  IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfnews"."file_attachment_sequence" ADD CONSTRAINT "fatseq_pk"
  PRIMARY KEY ("file_attachment_sequence_guid")
;

ALTER TABLE "wfnews"."file_attachment_sequence" ADD CONSTRAINT "fatseq_uk" UNIQUE ("source_object_name_code","source_object_unique_id")
;

CREATE INDEX "fatseq_soncd_idx" ON "wfnews"."file_attachment_sequence" ("source_object_name_code" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "wfnews"."file_attachment_sequence" ADD CONSTRAINT "fatseq_soncd_fk"
  FOREIGN KEY ("source_object_name_code") REFERENCES "wfnews"."source_object_name_code" ("source_object_name_code") ON DELETE No Action ON UPDATE No Action
;