/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0    */
/*  Created On : 22-Aug-2022 4:49:06 PM         */
/*  DBMS       : PostgreSQL             */
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfnews"."external_uri"
(
  "external_uri_guid" VARCHAR(36) NOT NULL,    -- EXTERNAL_URI_GUID is a unique identifier for the record.
  "source_object_name_code" varchar(10)  NOT NULL,    -- SOURCE_OBJECT_NAME_CODE: Is a foreign key to SOURCE_OBJECT_NAME_CODE: Source Object Name Code is a table to hold the name of the source object class that the attachment belongs to. Visually, the source object class is usually exposed via a user interface screen, so you can think of attachments being associated to a screen.  For instance, when an incident photo is attached to an incident, the code value in this table will be Incident, and the attachment would be viewable in the UI via the Incident page.   Current values: * Incident
  "source_object_unique_id" varchar(50) NOT NULL,    -- Source Object Unique Identifier is the actual primary key value of the source object that spawned the event.  This, along with the Source Object Name will fully identify what the event belongs to. 
  "external_uri_category_tag" varchar(50)  NOT NULL,    -- External URI Category Tag is used to categorize URI link using tags. Some example category tags are Video, News, Public Notices, Area Restrictions.   The field is purposely designed to provide a generic method of assigning tags as opposed to driving it by a code/lookup table.
  "external_uri_display_label" varchar(50)   NOT NULL,    -- External URI Display Label is the label to display for an external URI link.
  "external_uri" varchar(1000)   NULL,    -- External URI contains the URI for external content such as public notices, area restrictions, YouTube videos on an external site.
  "private_ind" varchar(1)   NOT NULL DEFAULT 'N',    -- Private Ind indicates whether the external URI is deemed private (Y) or not (N).
  "published_ind" varchar(1) NOT NULL DEFAULT 'N',    -- Published Ind indicates whether the external URI is published (Y) or not (N).   external URIs may be attached to a Source Object by a staff person, but not published until the source object has been deemed complete. It is a method to ensure URI are not shown in an application to general users prematurely.
  "primary_ind" varchar(1)  NOT NULL DEFAULT 'N', 
  "archived_ind" varchar(1)  NOT NULL DEFAULT 'N',    -- Archived Ind indicates whether the external URI is archived (Y) or not (N).
  "created_timestamp" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,    -- Created Timestamp is the date and time the record was created.
  "revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
  "create_user" varchar(64)  NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
  "create_date" timestamp NOT NULL DEFAULT current_date,    -- CREATE_DATE is the date and time the row of data was created.
  "update_user" varchar(64)  NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
  "update_date" timestamp NOT NULL DEFAULT current_date    -- UPDATE_DATE is the date and time the row of data was updated.
);

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "wfnews"."external_uri"
  IS 'External URI is used to store URI (Uniform Resource Identifier) to content that is external to the application, such as YouTube links, news article links, etc.. This table provides a generic mechanism to categorize and label such external links.  The table will also be used to track public notices, such as area restrictions, evacuation orders, evacuation alerts that relate to an incident directly or in a general geographic area.'
;

COMMENT ON COLUMN "wfnews"."external_uri"."external_uri_guid"
  IS 'EXTERNAL_URI_GUID is a unique identifier for the record.'
;

COMMENT ON COLUMN "wfnews"."external_uri"."source_object_name_code"
  IS 'SOURCE_OBJECT_NAME_CODE: Is a foreign key to SOURCE_OBJECT_NAME_CODE: Source Object Name Code is a table to hold the name of the source object class that the attachment belongs to. Visually, the source object class is usually exposed via a user interface screen, so you can think of attachments being associated to a screen.  For instance, when an incident photo is attached to an incident, the code value in this table will be Incident, and the attachment would be viewable in the UI via the Incident page.   Current values: * Incident'
;

COMMENT ON COLUMN "wfnews"."external_uri"."source_object_unique_id" 
  IS 'Source Object Unique Identifier is the actual primary key value of the source object that spawned the event.  This, along with the Source Object Name will fully identify what the event belongs to. '
;

COMMENT ON COLUMN "wfnews"."external_uri"."external_uri_category_tag"
  IS 'External URI Category Tag is used to categorize URI link using tags. Some example category tags are Video, News, Public Notices, Area Restrictions.   The field is purposely designed to provide a generic method of assigning tags as opposed to driving it by a code/lookup table.'
;

COMMENT ON COLUMN "wfnews"."external_uri"."external_uri_display_label"
  IS 'External URI Display Label is the label to display for an external URI link.'
;

COMMENT ON COLUMN "wfnews"."external_uri"."external_uri"
  IS 'External URI contains the URI for external content such as public notices, area restrictions, YouTube videos on an external site.'
;

COMMENT ON COLUMN "wfnews"."external_uri"."published_ind"
  IS 'Published Ind indicates whether the external URI is published (Y) or not (N).   external URIs may be attached to a Source Object by a staff person, but not published until the source object has been deemed complete. It is a method to ensure URI are not shown in an application to general users prematurely.'
;

COMMENT ON COLUMN "wfnews"."external_uri"."created_timestamp"
  IS 'Created Timestamp is the date and time the record was created.'
;

COMMENT ON COLUMN "wfnews"."external_uri"."private_ind"
  IS 'Private Ind indicates whether the external URI is deemed private (Y) or not (N).'
;

COMMENT ON COLUMN "wfnews"."external_uri"."primary_ind" 
  IS 'Primary Ind indicates whether the URI is the primary URI associated to a Source Object (Y) or not (N).  IE if there are multiple videos linked to an Incident, one video may be marked as primary video to show and promote in an application.'
;

COMMENT ON COLUMN "wfnews"."external_uri"."archived_ind"
  IS 'Archived Ind indicates whether the external URI is archived (Y) or not (N).'
;

COMMENT ON COLUMN "wfnews"."external_uri"."revision_count"
  IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfnews"."external_uri"."create_user"
  IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfnews"."external_uri"."create_date"
  IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfnews"."external_uri"."update_user"
  IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfnews"."external_uri"."update_date"
  IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfnews"."external_uri" ADD CONSTRAINT "exturi_pk"
  PRIMARY KEY ("external_uri_guid")
;

ALTER TABLE "wfnews"."external_uri" ADD CONSTRAINT "exturi_uk" UNIQUE ("source_object_name_code","source_object_unique_id", "external_uri_category_tag","external_uri_display_label")
;

CREATE INDEX "exturi_sonc_idx" ON "wfnews"."external_uri" ("source_object_name_code" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "wfnews"."external_uri" ADD CONSTRAINT "exturi_sonc_fk"
  FOREIGN KEY ("source_object_name_code") REFERENCES "wfnews"."source_object_name_code" ("source_object_name_code") ON DELETE No Action ON UPDATE No Action
;