name: _Run Jmeter Tests

env:
  ENVIRONMENT: dev
  NUM_USERS: 1
  NUM_ITERATIONS: 10

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: wait for new components to start
        run: ls && cat ../load-testing/WFNEWS_Load_Test.jmx && sleep 30
      
      - name: execute test
        uses: rbhadti94/apache-jmeter-action@v0.6.0
        with:
          testFilePath: ./load-testing/WFNEWS_Load_Test.jmx
          args: -Jthreads=${{ env.NUM_USERS }} -Jhost=${{ env.ENVIRONMENT }}.bcwildfireservices.com -Jiterations=${{ env.NUM_ITERATIONS }}

