# Action for compiling and zipping the lambdas

name: Lambda Compile and Zip

on:
  workflow_call:
    inputs:
      REGISTRY:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r active-fire-monitor.zip lambda/active-fire-monitor

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r area-restrictions-monitor.zip lambda/area-restrictions-monitor

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r bans-and-prohibitions-monitor.zip lambda/bans-and-prohibitions-monitor

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r evacuation-orders-monitor.zip lambda/evacuation-orders-monitor

      - name: Get timestamp
        run: |
          echo "{date}={$(date +'%Y-%m-%d-%H-%M')}" >> $GITHUB_STATE

      - name: Make staging directory, copy files
        run: |
          mkdir staging
          cp active-fire-monitor.zip staging/active-fire-monitor.zip
          echo ${{hashFiles('staging/active-fire-monitor.zip')}} >> staging/active-fire-monitor-hash
          cp area-restrictions-monitor.zip staging/area-restrictions-monitor.zip
          echo ${{hashFiles('staging/area-restrictions-monitor.zip')}} >> staging/area-restrictions-monitor-hash
          cp bans-and-prohibitions-monitor.zip staging/bans-and-prohibitions-monitor.zip
          echo ${{hashFiles('staging/bans-and-prohibitions-monitor.zip')}} >> staging/bans-and-prohibitions-monitor-hash
          cp evacuation-orders-monitor.zip staging/evacuation-orders-monitor.zip
          echo ${{hashFiles('staging/evacuation-orders-monitor.zip')}} >> staging/evacuation-orders-monitor-hash
          cp lambda/lambda-layer/python.zip staging/python.zip
          echo ${{hashFiles('staging/python.zip')}} >> staging/python-hash

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_S3_PUSH_ROLE }}
          role-session-name: wfnews-push-lambda
          aws-region: ca-central-1

      #requires a wfnews-lambda-env bucket
      - name: Upload S3
        id: S3
        run: |
          export enviro=${{ inputs.ENVIRONMENT }}
          aws s3 cp ./staging s3://wfnews-lambda-$(echo ${enviro,,}) --recursive
