on:
  workflow_call:
    inputs:
      DB_USER:
        required: true
        type: string

jobs:
  run liquibase:
    - uses: actions/checkout@v2
    
    - uses: liquibase/liquibase-github-action@v7
      with:
        operation: 'update'
        classpath: './database'
        changeLogFile: 'main-changelog.json'
        username: ${{ inputs.DB_USER }}
        password: ${{ secrets.DB_PASS }}
        url: ${{ secrets.WFNEWS_DB_URL }}
