on:
  workflow_call:
    inputs:
      DB_USER:
        required: true
        type: string

jobs:
  run_liquibase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: liquibase/liquibase-github-action@v7
        with:
          operation: 'update'
          classpath: './database'
          changeLogFile: 'main-changelog.json'
          username: ${{ inputs.DB_USER }}
          password: ${{ secrets.DB_PASS }}
          url: ${{ secrets.WFNEWS_DB_URL }}