name: Manual Terraform Run

on:
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        description: Image tag to use
        required: false
        default: latest

jobs:
  terragrunt-deploy-dev:
    uses: ./.github/workflows/terragrunt-deploy.yml
    with:
      DEFAULT_APPLICATION_ENVIRONMENT: DEV
      IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
      TARGET_ENV: dev

      MAX_RECEIVED_COUNT: 10
      VISIBILITY_TIMEOUT_SECONDS: 100

    secrets: inherit
