name: DEV Deploy - Manual Trigger

on:
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        required: true
        type: string
        
env:
  TF_VERSION: 1.5.3
  TG_VERSION: 0.48.4
  TG_SRC_PATH: terraform
  TFC_WORKSPACE: wfnews-dev
  REPOSITORY: ghcr.io

permissions:
  id-token: write
  contents: read

jobs:
  terragrunt-deploy-dev:
    uses: ./.github/workflows/terragrunt.yml
    with:
      DEFAULT_APPLICATION_ENVIRONMENT: DEV
      IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
      TARGET_ENV: dev

      MAX_RECEIVED_COUNT: 10
      VISIBILITY_TIMEOUT_SECONDS: 100

    secrets: inherit

