name: Plan using terragrunt

on:
  workflow_dispatch:
    inputs:
      DEFAULT_APPLICATION_ENVIRONMENT:
        required: true
        default: "DEV"
        type: string
      TARGET_ENV:
        required: true
        default: "dev"
        type: string
      RESOURCE_TERRAFORM_TYPE:
        required: true
        type: string
      RESOURCE_TO_UPDATE:
        required: true
        type: string
      NEW_OBJECT_ID :
        required: true
        type: string

env:
  TF_VERSION: 1.5.3
  TG_VERSION: 0.48.4
  TG_SRC_PATH: terraform
  TFC_WORKSPACE: wfnews-${{ inputs.TARGET_ENV }}
  REPOSITORY: ghcr.io

jobs:
  terragrunt-remove-resource:
    uses: ./.github/workflows/terragrunt.yml
    with:
      DEFAULT_APPLICATION_ENVIRONMENT: ${{ inputs.DEFAULT_APPLICATION_ENVIRONMENT }}
      COMMAND: state rm ${{inputs.RESOURCE_TERRAFORM_TYPE}}.${{ inputs.RESOURCE_TO_UPDATE }}
      IMAGE_TAG: latest
      TARGET_ENV: ${{ inputs.TARGET_ENV }}
      MAX_RECEIVED_COUNT: 10
      VISIBILITY_TIMEOUT_SECONDS: 100

    secrets: inherit

  terragrunt-import-resource:
    uses: ./.github/workflows/terragrunt.yml
    with:
      DEFAULT_APPLICATION_ENVIRONMENT: ${{ inputs.DEFAULT_APPLICATION_ENVIRONMENT }}
      COMMAND: import ${{inputs.RESOURCE_TERRAFORM_TYPE}}.${{ inputs.RESOURCE_TO_UPDATE }} ${{ inputs.NEW_OBJECT_ID }}
      IMAGE_TAG: latest
      TARGET_ENV: ${{ inputs.TARGET_ENV }}
      MAX_RECEIVED_COUNT: 10
      VISIBILITY_TIMEOUT_SECONDS: 100