name: Plan using terragrunt

on:
  workflow_dispatch:
    inputs:
      DEFAULT_APPLICATION_ENVIRONMENT:
        required: true
        default: "TEST"
        type: string
      TARGET_ENV:
        required: true
        default: "test"
        type: string
      IMAGE_TAG:
        required: true
        default: main
        type: string
env:
  TF_VERSION: 1.5.3
  TG_VERSION: 0.48.4
  TG_SRC_PATH: terraform
  TFC_WORKSPACE: wfnews-${{ inputs.TARGET_ENV }}
  REPOSITORY: ghcr.io

jobs:
  terragrunt-plan:
    uses: ./.github/workflows/terragrunt.yml
    with:
      DEFAULT_APPLICATION_ENVIRONMENT: ${{ inputs.DEFAULT_APPLICATION_ENVIRONMENT }}
      COMMAND: plan
      IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
      TARGET_ENV: ${{ inputs.TARGET_ENV }}
    secrets: inherit